# Generated by Django 4.2.6 on 2023-10-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_name', models.CharField(max_length=100)),
                ('request_number', models.IntegerField()),
                ('mail_number', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('data_length', models.IntegerField()),
                ('aggregate_number', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
